spring:
  application:
    name: question-service
  config:
    import: optional:file:./preguntas-backend/shared-config/application-db-secrets.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/questions_db
    username: postgres
    password: ${dataConfig.password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: ucr.ac.cr.learningcommunity.questionservice.events

server:
  port: ${SERVER_PORT:8082}


eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

ia-service:
  url: http://localhost:8083/api/private/ia

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml