spring:
  application:
    name: question-service
  datasource:
    url: jdbc:postgresql://localhost:5432/questions_db
    username: postgres
    password: vacalola
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${SERVER_PORT:8082}


eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: tru

ia-service:
  url: http://localhost:8083/api/private/ia

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml