server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: ia-service
          uri: lb://ia-service
          predicates:
            - Path=/api/public/ia/**, /api/private/ia/**
          metadata:
            cors:
              allowedOrigins: "http://localhost:5173"
              allowedMethods:
                - GET
                - POST
                - DELETE
                - PUT
                - OPTIONS
              allowedHeaders: '*'
        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/api/public/questions/**, /api/private/questions/**
          metadata:
            cors:
              allowedOrigins: "http://localhost:5173"
              allowedMethods:
                - GET
                - POST
                - DELETE
                - PUT
                - OPTIONS
              allowedHeaders: '*'
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/public/auth/**, /api/private/auth/**
          metadata:
            cors:
              allowedOrigins: "http://localhost:5173"
              allowedMethods:
                - GET
                - POST
                - DELETE
                - PUT
                - OPTIONS
              allowedHeaders: '*'
logging:
  level:
    org:
      springframework:
        web: DEBUG

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
jwt:
  secret: KXiUPknkoVDCHdNrrYnxmA5oQLbv+LE7eHG8vkk71fjEPq0lmlZKwBhUVLUqKSmGam8P4kWxXKTGCDRgpZ5BMA==
