server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "${ALLOWED_ORIGINS:http://preguntas-frontend:5173}"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ia-service
          uri: lb://ia-service
          predicates:
            - Path=/api/public/ia/**, /api/private/ia/**
        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/api/public/questions/**, /api/private/questions/**
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/public/auth/**, /api/private/auth/**

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

jwt:
  secret: ${JWT_SECRET}