spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres-auth:5432/auth_db
    username: postgres
    password: ${POSTGRES_PASSWORD}
  kafka:
    bootstrap-servers: kafka:29092
  redis:
    host: redis
    port: 6379

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: authentication-service
logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
jwt:
  secret: ${JWT_SECRET}