INSERT INTO category (name) VALUES
    ('Matemáticas'),
    ('Geometría'),
    ('Álgebra'),
    ('Trigonometría'),
    ('Cálculo'),
    ('Estadística'),
    ('Probabilidad'),
    ('Física'),
    ('Química'),
    ('Biología'),
    ('Astronomía'),
    ('Geología'),
    ('Ciencias Naturales'),
    ('Ecología'),
    ('Informática'),
    ('Programación'),
    ('Redes'),
    ('Base de Datos'),
    ('Ciberseguridad'),
    ('Sistemas Operativos'),
    ('Lengua Española'),
    ('Gramática'),
    ('Ortografía'),
    ('Literatura'),
    ('Comprensión Lectora'),
    ('Redacción'),
    ('Historia'),
    ('Geografía'),
    ('Cívica'),
    ('Educación Religiosa'),
    ('Filosofía'),
    ('Lógica'),
    ('Psicología'),
    ('Sociología'),
    ('Antropología'),
    ('Economía'),
    ('Contabilidad'),
    ('Administración'),
    ('Negocios'),
    ('Marketing'),
    ('Publicidad'),
    ('Recursos Humanos'),
    ('Finanzas'),
    ('Banca'),
    ('Inversiones'),
    ('Emprendimiento'),
    ('Derecho'),
    ('Derechos Humanos'),
    ('Constitución'),
    ('Política'),
    ('Gobierno'),
    ('Educación para la Paz'),
    ('Educación Sexual'),
    ('Salud'),
    ('Nutrición'),
    ('Medicina'),
    ('Primeros Auxilios'),
    ('Anatomía'),
    ('Deportes'),
    ('Educación Física'),
    ('Entrenamiento'),
    ('Yoga'),
    ('Meditación'),
    ('Arte'),
    ('Pintura'),
    ('Música'),
    ('Teatro'),
    ('Cine'),
    ('Fotografía'),
    ('Dibujo'),
    ('Diseño'),
    ('Arquitectura'),
    ('Ingeniería Civil'),
    ('Ingeniería Industrial'),
    ('Ingeniería Electrónica'),
    ('Ingeniería Mecánica'),
    ('Robótica'),
    ('Automatización'),
    ('Inteligencia Artificial'),
    ('Aprendizaje Automático'),
    ('Procesamiento de Lenguaje Natural'),
    ('Ciencias de Datos'),
    ('Big Data'),
    ('Álgebra Lineal'),
    ('Ecuaciones Diferenciales'),
    ('Topología'),
    ('Teoría de Números'),
    ('Matemática Discreta'),
    ('Criptografía'),
    ('Seguridad Informática'),
    ('Desarrollo Web'),
    ('Diseño de Interfaces'),
    ('Experiencia de Usuario'),
    ('Desarrollo Móvil'),
    ('Aplicaciones Híbridas'),
    ('Testing de Software'),
    ('DevOps'),
    ('Cloud Computing'),
    ('AWS'),
    ('Azure'),
    ('Google Cloud'),
    ('Linux'),
    ('Shell Scripting'),
    ('Git'),
    ('Control de Versiones'),
    ('Metodologías Ágiles'),
    ('Scrum'),
    ('Kanban'),
    ('Gestión de Proyectos'),
    ('Toma de Decisiones'),
    ('Pensamiento Crítico'),
    ('Resolución de Problemas'),
    ('Creatividad'),
    ('Innovación'),
    ('Comunicación Efectiva'),
    ('Trabajo en Equipo'),
    ('Liderazgo'),
    ('Negociación'),
    ('Inteligencia Emocional'),
    ('Autoestima'),
    ('Motivación'),
    ('Orientación Vocacional'),
    ('Cuidado del Medio Ambiente'),
    ('Sostenibilidad'),
    ('Cambio Climático'),
    ('Energías Renovables'),
    ('Consumo Responsable'),
    ('Educación Financiera'),
    ('Ahorro'),
    ('Presupuestos'),
    ('Créditos'),
    ('Impuestos'),
    ('Planeación Financiera'),
    ('Cálculo Financiero'),
    ('Matemática Financiera'),
    ('Física Moderna'),
    ('Termodinámica'),
    ('Óptica'),
    ('Electromagnetismo'),
    ('Mecánica Cuántica'),
    ('Relatividad'),
    ('Neurociencia'),
    ('Genética'),
    ('Microbiología'),
    ('Virología'),
    ('Bioética'),
    ('Biotecnología'),
    ('Zoología'),
    ('Botánica'),
    ('Oceanografía'),
    ('Meteorología'),
    ('Cartografía'),
    ('Geopolítica'),
    ('Historia de Costa Rica'),
    ('Historia Universal'),
    ('Prehistoria'),
    ('Edad Antigua'),
    ('Edad Media'),
    ('Edad Moderna'),
    ('Edad Contemporánea'),
    ('Mitos y Leyendas'),
    ('Religiones del Mundo'),
    ('Cultura Popular'),
    ('Valores'),
    ('Cultura Digital'),
    ('Tecnología Educativa'),
    ('Herramientas Digitales'),
    ('Educación Virtual'),
    ('Aprendizaje Autónomo'),
    ('Estilos de Aprendizaje'),
    ('Memorización'),
    ('Técnicas de Estudio'),
    ('Mapas Mentales'),
    ('Organización del Tiempo'),
    ('Evaluación del Aprendizaje'),
    ('Planeación Docente'),
    ('Psicopedagogía'),
    ('Neuroeducación'),
    ('Inclusión Educativa'),
    ('Diversidad'),
    ('Educación Especial'),
    ('Gamificación'),
    ('Aprendizaje Basado en Proyectos');