INSERT INTO category (name) VALUES
('Nanotecnología'),
('Astrobiología'),
('Ingeniería de Software'),
('Arquivística'),
('Semiología'),
('Antropología Forense'),
('Patología'),
('Toxicología'),
('Dermatología'),
('Endocrinología'),
('Reumatología'),
('Oncología'),
('Geriatría'),
('Pediatría'),
('Odontología'),
('Ortodoncia'),
('Anestesiología'),
('Farmacología'),
('Bioquímica'),
('Fisiología'),
('Histología'),
('Embriología'),
('Citología'),
('Terapia Física'),
('Terapia Ocupacional'),
('Fonoaudiología'),
('Logopedia'),
('Audiología'),
('Optometría'),
('Kinesiología'),
('Biomecánica'),
('Ingeniería Biomédica'),
('Neuropsicología'),
('Psicoanálisis'),
('Terapia Cognitivo Conductual'),
('Tanatología'),
('Sexología'),
('Epidemiología'),
('Salud Pública'),
('Ingeniería Ambiental'),
('Gestión Ambiental'),
('Impacto Ambiental'),
('Ingeniería Agronómica'),
('Agroecología'),
('Fitotecnia'),
('Zootecnia'),
('Horticultura'),
('Silvicultura'),
('Ingeniería Forestal'),
('Gestión de Recursos Naturales'),
('Energía Nuclear'),
('Energía Eólica'),
('Energía Solar'),
('Geotermia'),
('Hidráulica'),
('Hidrología'),
('Oceanografía Física'),
('Geofísica'),
('Mineralogía'),
('Petrología'),
('Paleontología'),
('Arqueología'),
('Egiptología'),
('Numismática'),
('Heráldica'),
('Archivística'),
('Bibliotecología'),
('Ciencia de la Información'),
('Documentación'),
('Periodismo Científico'),
('Comunicación Organizacional'),
('Lingüística Aplicada'),
('Fonética'),
('Morfología'),
('Sintaxis'),
('Semántica'),
('Pragmática'),
('Lexicografía'),
('Glotología'),
('Traducción'),
('Interpretación'),
('Literatura Comparada'),
('Crítica Literaria'),
('Poética'),
('Narratología'),
('Mitología'),
('Teología'),
('Eclesiología'),
('Historia del Arte'),
('Estética'),
('Apreciación Musical'),
('Dirección Orquestal'),
('Composición Musical'),
('Musicología'),
('Diseño Gráfico'),
('Diseño Industrial'),
('Diseño de Moda'),
('Diseño de Producto'),
('Diseño UX'),
('Diseño UI'),
('Ergonomía'),
('Producción Multimedia'),
('Animación 2D'),
('Animación 3D'),
('Realidad Virtual'),
('Realidad Aumentada'),
('Videojuegos'),
('Gamificación Educativa'),
('Simulación por Computadora'),
('Visualización de Datos'),
('Minería de Datos'),
('Machine Learning'),
('Deep Learning'),
('Redes Neuronales'),
('Visión por Computador'),
('Cómputo Cuántico'),
('Criptomonedas'),
('Blockchain'),
('Contratos Inteligentes'),
('Fintech'),
('RegTech'),
('InsurTech'),
('Ciberseguridad Industrial'),
('Pentesting'),
('Ingeniería Social'),
('Ingeniería del Conocimiento'),
('Ontologías'),
('Web Semántica'),
('Metaverso'),
('Desarrollo Full Stack'),
('Testing Automatizado'),
('QA Manual'),
('Modelado UML'),
('Arquitectura Hexagonal'),
('Patrones de Diseño'),
('Microservicios'),
('API REST'),
('GraphQL'),
('gRPC'),
('WebSockets'),
('CI/CD'),
('Terraform'),
('Kubernetes'),
('Docker'),
('OpenShift'),
('Ansible'),
('Jenkins'),
('Apache Kafka'),
('RabbitMQ'),
('BigQuery'),
('Snowflake'),
('Redshift'),
('Hadoop'),
('Spark'),
('Elasticsearch'),
('Logstash'),
('Kibana'),
('Prometheus'),
('Grafana'),
('DataOps'),
('MLOps'),
('DevSecOps'),
('Gobernanza de Datos'),
('Calidad de Datos'),
('Arquitectura de Datos'),
('Ingeniería de Datos'),
('Análisis Predictivo'),
('Análisis Prescriptivo'),
('Business Intelligence'),
('Tableau'),
('Power BI'),
('Google Data Studio'),
('Excel Avanzado'),
('Estadística Inferencial'),
('Métodos Numéricos'),
('Simulación Monte Carlo'),
('Investigación de Operaciones'),
('Teoría de Juegos'),
('Optimización Lineal'),
('Algoritmos Genéticos'),
('Heurísticas'),
('Sistemas Multiagente'),
('Lógica Difusa'),
('Sistemas Expertos'),
('Teoría del Caos'),
('Teoría de la Complejidad'),
('Teoría de la Información'),
('Teoría de Categorías'),
('Teoría de Sistemas'),
('Cibernética'),
('Dinámica de Sistemas'),
('Ingeniería de Requisitos'),
('Gestión de Configuraciones'),
('Calidad de Software'),
('Normas ISO'),
('SCRUM Master'),
('Product Owner'),
('Gestión de Riesgos'),
('PMBOK'),
('Lean'),
('Six Sigma'),
('Kaizen'),
('Just in Time'),
('Manufactura Esbelta'),
('Industria 4.0'),
('Smart Cities'),
('Sistemas Embebidos'),
('Electrónica de Potencia'),
('Microcontroladores'),
('PLC'),
('SCADA'),
('Automatización Industrial'),
('Mecatrónica'),
('Neumática'),
('Hidráulica Industrial'),
('CAD'),
('CAE'),
('CAM'),
('Diseño Asistido por Computadora'),
('Ingeniería de Transporte'),
('Logística'),
('Cadena de Suministro'),
('Gestión de Inventarios'),
('Comercio Electrónico'),
('Transformación Digital'),
('Marketing Digital'),
('SEO'),
('SEM'),
('Content Marketing'),
('Email Marketing'),
('Social Media'),
('UX Writing'),
('Branding'),
('Neuromarketing'),
('Psicología del Consumidor'),
('Antropología del Consumo'),
('Cultura Organizacional'),
('Clima Laboral'),
('Gestión del Talento Humano'),
('Gestión del Conocimiento'),
('Liderazgo Transformacional'),
('Coaching'),
('Mentoring'),
('Formación Docente'),
('Andragogía'),
('Educación STEAM'),
('Neurodidáctica'),
('Educación Inclusiva'),
('Evaluación Educativa'),
('Políticas Educativas'),
('Currículo Escolar'),
('Didáctica'),
('TIC en Educación'),
('B-Learning'),
('M-Learning');