spring:
  application:
    name: ia-service
  datasource:
    url: jdbc:postgresql://postgres-ia:5432/ia_db
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        model: text-embedding-ada-002
        options:
          encodingFormat: float
          dimensions: 1536

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: ia-service

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml