spring:
  application:
    name: ia-service

  config:
    import: classpath:/application-secret.yml

  ai:
    openai:
      api-key: ${openai.api-key}
      embedding:
        model: text-embedding-ada-002
        options:
          encodingFormat: float
          dimensions: 1536
    model:
      embedding: openai

  datasource:
    url: jdbc:postgresql://localhost:5432/ia_db
    username: postgres
    password: vacalola
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${SERVER_PORT:8083}


eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml