spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: ${SENDGRID_USERNAME:apikey}
    password: ${SENDGRID_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: ${EMAIL_FROM:contilearningcommunity.cr@gmail.com}

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: email-service
    preferIpAddress: true

topic:
  client:
    name: ${KAFKA_TOPIC:user-registered-topic2}

server:
  port: 8085