name: CI/CD Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [ia-service, question-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ${{ matrix.service }}/gradlew

      - name: Run tests for ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: ./gradlew test

  docker-build-and-push:
    needs: test-and-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          declare -a services=(
            authentication-service
            email-service
            eureka
            gateway
            ia-service
            question-service
          )

          VERSION_TAG=1.0
          for service in "${services[@]}"; do
            IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/${service}"

            echo "Building $IMAGE_NAME with tags 'latest' and '$VERSION_TAG'..."
            docker build \
              -t $IMAGE_NAME:latest \
              -t $IMAGE_NAME:$VERSION_TAG \
              ./$(echo $service)

            echo "Pushing $IMAGE_NAME:latest"
            docker push $IMAGE_NAME:latest

            echo "Pushing $IMAGE_NAME:$VERSION_TAG"
            docker push $IMAGE_NAME:$VERSION_TAG
          done
